### ISSUE TITLE
Dev environment needs to be a Data Science Project

### ISSUE THREAD

**Issue by brianjball** [redhat-na-ssa/ai-golden-path#2]
The project needs the following annotation to be added to RHOAI:
```yaml
metadata:
  labels:
    opendatahub.io/dashboard: 'true'
```
